"use client";

import { Button } from "@/components/core/button";
import { useColorStore } from "@/lib/store";
import { generateColors, generateCssVariables } from "coloris-js";
import { Brackets, ChevronLeft } from "lucide-react";
import { useTransitionRouter } from "next-view-transitions";

export default function Tokens() {
  const { accent, background } = useColorStore();
  const cssVariables = generateCssVariables(
    generateColors({ appearance: "light", accent, background }),
  );
  const router = useTransitionRouter();

  return (
    <article className="prose prose-pre:bg-secondary prose-code:text-fg-primary prose-h2:m-0 prose-h2:font-medium">
      <Button
        variant="outline"
        size="sm"
        className="mb-4"
        onClick={() => router.back()}
      >
        <ChevronLeft className="size-4" />
        <span>Back</span>
      </Button>
      <div className="flex items-center gap-x-4">
        <span className="border-divider-primary inline-flex size-12 items-center justify-center rounded-full border">
          <Brackets />
        </span>
        <h2>Tokens</h2>
      </div>

      <p>
        This is the CSS variables generated by coloris.js. You can copy and
        paste them into your project.
      </p>
      <pre>
        <code>{cssVariables}</code>
      </pre>
    </article>
  );
}
